/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package familytree;

import javax.swing.JOptionPane;

/**
 *
 * @author szeke
 */
public class ModositasFrame extends javax.swing.JFrame {

    private Szemely szemely;
    /**
     * Creates new form ModositasFrame
     */
    public ModositasFrame(Szemely sz) {
        szemely = sz;
        initComponents();
    }
    public ModositasFrame() {
        initComponents();
    }
    
    private void updateSzemely(){
        boolean voltSzulo = true;
        boolean result = false;
        if(this.szemely.getAnya() == null && this.szemely.getAnya() == null){
            voltSzulo = false;
        }
        this.szemely.setAnya(anyaMezo.getText());
        this.szemely.setApa(apaMezo.getText());
        this.szemely.setHalalhely(halalHelyMezo.getText());
        this.szemely.setHalalido(halalIdoMezo.getText());
        this.szemely.setLany(lanyBox.isSelected());
        this.szemely.setNev(nevMezo.getText());
        this.szemely.setSzulhely(szulHelyMezo.getText());
        this.szemely.setSzulido(szulIdoMezo.getText());
        
        
        result = FamilyTreeFrame.dh.updateSzemely(this.szemely, voltSzulo);
        if(result){
            JOptionPane.showMessageDialog(null, "A módosítás megtörtént!");
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        anyaMezo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apaMezo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mentesGomb = new javax.swing.JButton();
        nevMezo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lanyBox = new javax.swing.JCheckBox();
        szulHelyMezo = new javax.swing.JTextField();
        szulIdoMezo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        halalIdoMezo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        halalHelyMezo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        szemelyiSzamMezo = new javax.swing.JTextField();
        megseGomb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adatmódosítás");
        setLocation(new java.awt.Point(1000, 200));
        setResizable(false);

        jLabel4.setText("Anya személyi száma:");

        anyaMezo.setText(this.szemely.getAnya());

        jLabel5.setText("Apa személyi száma:");

        apaMezo.setText(this.szemely.getApa());

        jLabel1.setText("Név:");

        mentesGomb.setBackground(new java.awt.Color(0, 204, 0));
        mentesGomb.setText("Mentés");
        mentesGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentesGombActionPerformed(evt);
            }
        });

        nevMezo.setText(this.szemely.getNev());
        nevMezo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevMezoActionPerformed(evt);
            }
        });

        jLabel2.setText("Születési hely:");

        jLabel3.setText("Születési idõ:");

        lanyBox.setSelected(this.szemely.isLany());
        lanyBox.setText("Lány");
        lanyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanyBoxActionPerformed(evt);
            }
        });

        szulHelyMezo.setText(this.szemely.getSzulhely());

        szulIdoMezo.setText(this.szemely.getSzulido());

        jLabel9.setText("Elhalálozás ideje:");

        halalIdoMezo.setText(this.szemely.getHalalido());

        jLabel10.setText("Elhalálozás helye:");

        halalHelyMezo.setText(this.szemely.getHalalhely());
        halalHelyMezo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halalHelyMezoActionPerformed(evt);
            }
        });

        jLabel11.setText("Személyi szám:");

        szemelyiSzamMezo.setEditable(false);
        szemelyiSzamMezo.setText(this.szemely.getSzemelyiSzam());
        szemelyiSzamMezo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szemelyiSzamMezoActionPerformed(evt);
            }
        });

        megseGomb.setBackground(new java.awt.Color(255, 51, 51));
        megseGomb.setText("Mégse");
        megseGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                megseGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(szulIdoMezo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(szulHelyMezo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(nevMezo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lanyBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anyaMezo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(apaMezo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(halalHelyMezo))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(szemelyiSzamMezo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(halalIdoMezo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(mentesGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(megseGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(szemelyiSzamMezo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nevMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lanyBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(szulHelyMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(szulIdoMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(anyaMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(apaMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(halalIdoMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(halalHelyMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(megseGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mentesGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nevMezoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevMezoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nevMezoActionPerformed

    private void lanyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lanyBoxActionPerformed

    private void halalHelyMezoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halalHelyMezoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halalHelyMezoActionPerformed

    private void szemelyiSzamMezoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szemelyiSzamMezoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_szemelyiSzamMezoActionPerformed

    private void megseGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_megseGombActionPerformed
        dispose();
    }//GEN-LAST:event_megseGombActionPerformed

    private void mentesGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentesGombActionPerformed
        updateSzemely();
        dispose();
    }//GEN-LAST:event_mentesGombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModositasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModositasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModositasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModositasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModositasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anyaMezo;
    private javax.swing.JTextField apaMezo;
    private javax.swing.JTextField halalHelyMezo;
    private javax.swing.JTextField halalIdoMezo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox lanyBox;
    private javax.swing.JButton megseGomb;
    private javax.swing.JButton mentesGomb;
    private javax.swing.JTextField nevMezo;
    private javax.swing.JTextField szemelyiSzamMezo;
    private javax.swing.JTextField szulHelyMezo;
    private javax.swing.JTextField szulIdoMezo;
    // End of variables declaration//GEN-END:variables
}
